# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0431c63efee59e52134e8e3fdcc6893404cbca7aa13b43657885cccfc5431e9041fb5743c21e28e6f4ad29e925941822729c7635a0cdf8428ba7ada05fb34e75

test:
  secret_key_base: 22eb22e0d1c9ea07969dd3e724bb1ace3b70b8971da3619449b8cf7df0c88655ea747f8be0f8347eb14a14f71a962dbad51e48f3718f7c5ab74ac8f9476b0ccd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
